sudo: required

language: node_js
  - "4"

services:
  - docker

before_install:
- docker build -t alekster/traveler-front:v_$TRAVIS_BUILD_NUMBER .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push alekster/traveler-front;
    fi

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: scripts/deployToStaging.sh
    on:
      branch: dev
  # deploy master to production
  - provider: script
    script: scripts/deployToProduction.sh
    on:
      branch: master
